target 'NGO' do
  
  use_frameworks!

  # Pods for NGO
  pod 'MaterialComponents/TextFields'
  pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'SwiftyJSON'
pod 'SVProgressHUD'

end
